// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBBCWuPR7Im5QVR0OIpdhlBDjzKUMj4I',
    appId: '1:286473724516:web:c1cdd0e0bac0791a743571',
    messagingSenderId: '286473724516',
    projectId: 'carenest-1519f',
    authDomain: 'carenest-1519f.firebaseapp.com',
    storageBucket: 'carenest-1519f.firebasestorage.app',
    measurementId: 'G-JRHXZTQ09R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdVTr91OL_DEoM2jELNyynM0nQVpS-Wf4',
    appId: '1:286473724516:android:7aa0ab77188f1f91743571',
    messagingSenderId: '286473724516',
    projectId: 'carenest-1519f',
    storageBucket: 'carenest-1519f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBUmfez565zv9WdRFgVSWGwLx5Lvpsvc',
    appId: '1:286473724516:ios:a35c592b4cd79258743571',
    messagingSenderId: '286473724516',
    projectId: 'carenest-1519f',
    storageBucket: 'carenest-1519f.firebasestorage.app',
    iosClientId: '286473724516-voiqk9d5df2sb45ouhl6301goqj2kgcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBUmfez565zv9WdRFgVSWGwLx5Lvpsvc',
    appId: '1:286473724516:ios:a35c592b4cd79258743571',
    messagingSenderId: '286473724516',
    projectId: 'carenest-1519f',
    storageBucket: 'carenest-1519f.firebasestorage.app',
    iosClientId: '286473724516-voiqk9d5df2sb45ouhl6301goqj2kgcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBBCWuPR7Im5QVR0OIpdhlBDjzKUMj4I',
    appId: '1:286473724516:web:83a87a90d32ab422743571',
    messagingSenderId: '286473724516',
    projectId: 'carenest-1519f',
    authDomain: 'carenest-1519f.firebaseapp.com',
    storageBucket: 'carenest-1519f.firebasestorage.app',
    measurementId: 'G-8PT7KP9PYG',
  );
}
